spring:
  application:
    name: abiooc-inventaire

  datasource:
    url: jdbc:postgresql://localhost:5432/abiooc_inventory
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
logging:
  level:
    com.abiooc: DEBUG
    org.springframework.web: INFO
    org.hibernate: DEBUG